#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

echo "Building Rust executables..."
cargo build --release

echo "Installing executables to /usr/local/bin..."
sudo cp ./target/release/hnt-llm /usr/local/bin/hnt-llm
sudo cp ./target/release/hnt-escape /usr/local/bin/hnt-escape

echo "rust/build: installed hnt-llm in /usr/local/bin/"
echo "rust/build: installed hnt-escape in /usr/local/bin/"
