#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

# hnt-llm is implicitly built by edit
cd edit
echo "build: running edit/build"
./build
cd - > /dev/null

cd agent
echo "build: running agent/build"
./build

echo "build: successfully installed all of hinata"
