#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

# hnt-llm is implicitly built by edit
echo "root/build: running edit/build"
./edit/build

echo "root/build: running agent/build"
./agent/build

echo "root/build: successfully installed all of hinata"
