#!/bin/sh -e

cd "$(dirname "$0")"

# Ensure hnt-chat is installed
if ! which hnt-chat > /dev/null 2>&1
then
	echo "hnt-web/build: hnt-chat required. installing..."
	../install.sh

	# -e exits if not found
	which hnt-chat > /dev/null
fi

# Install web assets
web="${XDG_DATA_HOME:-$HOME/.local/share}/hinata/web"
mkdir -p "$web"
cp -r static/* "$web/"

echo "hnt-web/build: installed hnt-web assets in $web"

# Build Go binary
echo "hnt-web/build: building Go binary..."
go build -o ../bin/hnt-web.out ./cmd/hnt-web

echo "hnt-web/build: completed"