#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

# gcc -lcurl -ljansson main.c -o ./hnt-llm
gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	-lcurl -ljansson \
	main.c -o ./hnt-llm

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	escape.c -o ./hnt-escape

sudo cp ./hnt-llm ./hnt-escape /usr/local/bin/
echo "llm/build: compiled hnt-llm and hnt-escape"
