#!/bin/sh -e
cd "$(dirname "$0")"

if ! which hnt-llm > /dev/null 2>&1
then
	echo "chat/build: hnt-llm not found. compiling..."
	cd ../llm
	./build
	cd -
fi

chmod +x ./hnt-chat.py
sudo cp ./hnt-chat.py /usr/local/bin/hnt-chat
echo "chat/build: installed hnt-chat"
