#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	main.c -o ./llm-pack

sudo cp ./llm-pack /usr/local/bin/
