#!/bin/sh -e

# user config =================================================
inst="Please update the favourite number to 5. And please add a second print statement to print the number one higher than my favourite number. Then please update the README"
source_files="test/main.py test/docs/README.md"

# pre-determined =================================================
system_f=../prompts/01-targetreplace.md
user_f=$(mktemp -u)
gen_f=$(mktemp -u)

echo "User request:
$inst

Source reference:" >> "$user_f"
llm-pack $source_files >> "$user_f"

system=$(cat "$system_f")
hnt -s "$system" < "$user_f" | tee "$gen_f"

hnt-apply $source_files < "$gen_f"

rm "$user_f" "$gen_f"
