#!/bin/sh

[ "$1" ] && comment="here is a brief comment by the developer (only relevant to deciding on the commit message): $@"

export HINATA_LLM_MODEL=openrouter/google/gemini-2.5-pro
hnt-agent --no-confirm -m "please do the following
1. check the repo status
2. check if no changes are staged
	if yes
		stage ALL the unstaged changes
	if not
		don't make any changes to what is staged and what is not

3. view the diff *of the staged changes* only
4. commit those staged changes with a meaningful message
	include that it was committed by \"hnt-agent via util/commit\"
5. report to the user that you're finished
please don't take any other action unless the user explicitly gives you further instructions

$comment

if there are any unstaged changes at this point, leave them as is"

git push
