#!/bin/sh

if ! git config get user.name > /dev/null
then
	notify-send "set user.name for $PWD!"
	exit 1
fi

if ! git config get user.email > /dev/null
then
	notify-send "set user.email for $PWD!"
	exit 1
fi

[ "$CLAUDE" ] && CLAUDE="Co-Authored-By: Claude <noreply@anthropic.com>"

[ "$1" ] && comment="here is a brief comment by the developer (only relevant to deciding on the commit message): $@"

# export HINATA_AGENT_MODEL=openrouter/google/gemini-2.5-pro
export HINATA_AGENT_MODEL=openrouter/moonshotai/kimi-k2
export HNT_AGENT_DEBUG=1

# hnt-agent --shell-box --auto-exit -m "please do the following
hnt-agent --shell-box --yes --auto-exit -m "please do the following
1. check the repo status
2. check if any changes are staged
	if yes (there are >0 changes staged)
		don't make any changes to what is staged and what is not
	if not (there are 0 changes staged)
		stage ALL the unstaged changes

3. view the diff *of the staged changes* only
4. commit those staged changes with a meaningful message
	include at the end:
	Co-Authored-By: Hinata <veil@sucralose.moe>
	$CLAUDE
5. report to the user that you're finished
please don't take any other action unless the user explicitly gives you further instructions

$comment

if there are any unstaged changes at this point, leave them as is"

git push
