#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	headlesh.c -o ./headlesh

mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/hinata/headlesh"
sudo cp ./headlesh /usr/local/bin/

echo "headlesh/build: built headlesh"
