#!/bin/sh -e

prompts_dir=$XDG_CONFIG_HOME/hinata/prompts
bin=/usr/local/bin/

mkdir -p "$prompts_dir"
cp prompts/* "$prompts_dir"
echo "build: installed prompts in $prompts_dir"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	hnt-apply.c -o ./hnt-apply

sudo cp ./hnt-apply "$bin"
echo "build: installed hnt-apply in $bin"

chmod +x ./hnt-edit
sudo cp ./hnt-edit "$bin"
echo "build: installed hnt-edit in $bin"
