#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

if ! which hnt > /dev/null 2>&1
then
	echo "build: hnt not found. compiling..."
	cd ../hnt
	./build
	cd -
fi

if ! which llm-pack > /dev/null 2>&1
then
	ehco "build: llm-pack not found. compiling..."
	cd llm-pack
	./build
	cd -
fi

prompts_dir=$XDG_CONFIG_HOME/hinata/prompts
bin=/usr/local/bin/

mkdir -p "$prompts_dir"
cp prompts/* "$prompts_dir"
echo "build: installed prompts in $prompts_dir"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	hnt-apply.c -o ./hnt-apply

sudo cp ./hnt-apply "$bin"
echo "build: installed hnt-apply in $bin"

chmod +x ./hnt-edit
sudo cp ./hnt-edit "$bin"
echo "build: installed hnt-edit in $bin"
