#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

if ! which hlmd-st > /dev/null 2>&1
then
	if which uv > /dev/null 2>&1
	then
		echo "edit/build: uv installed but hlmd-st not found. installing..."
		cd ../fmt/highlight
		./build
		cd -
	else
		echo "edit/build: not installing hldm-st because uv not found. lol what are you doing"
	fi
fi

if ! which hnt-chat > /dev/null 2>&1
then
	echo "edit/build: hnt-chat not found. installing..."
	cd ../chat
	./build
	cd -
fi

if ! which hnt-escape > /dev/null 2>&1
then
	echo "edit/build: hnt-escape not found. compiling..."
	cd ../llm
	./build
	cd -
fi

if ! which llm-pack > /dev/null 2>&1
then
	echo "edit/build: llm-pack not found. compiling..."
	cd llm-pack
	./build
	cd -
fi

prompts_dir=$XDG_CONFIG_HOME/hinata/prompts
bin=/usr/local/bin

mkdir -p "$prompts_dir"
cp prompts/* "$prompts_dir"
echo "edit/build: installed prompts in $prompts_dir"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	hnt-apply.c -o ./hnt-apply

sudo cp ./hnt-apply "$bin/"
echo "edit/build: installed hnt-apply in $bin/"

chmod +x ./hnt-edit.py
sudo cp ./hnt-edit.py "$bin/hnt-edit"
echo "edit/build: installed hnt-edit in $bin/"
