#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	tui-select.c -o ./tui-select.out

mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/hinata/tui-select"
sudo cp ./tui-select.out /usr/local/bin/

echo "tui/build: built tui-select"
