#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

if ! which headlesh > /dev/null 2>&1
then
	echo "agent/build: headlesh not found. compiling..."
	./headlesh/build
fi

if ! which tui-select > /dev/null 2>&1
then
	echo "agent/build: tui-select not found. compiling..."
	../util/tui/build
fi

prompts_dir=${XDG_CONFIG_HOME:-$HOME/.config}/hinata/prompts
bin=/usr/local/bin

mkdir -p "$prompts_dir"
cp prompts/* "$prompts_dir"
echo "agent/build: installed prompts in $prompts_dir"

chmod +x ./hnt-shell-apply.py
chmod +x ./hnt-agent.py

sudo cp ./hnt-shell-apply.py "$bin/hnt-shell-apply"
echo "agent/build: installed hnt-shell-apply in $bin/"

sudo cp ./hnt-agent.py "$bin/hnt-agent"
echo "agent/build: installed hnt-agent in $bin/"
