#!/bin/sh -e

# Change to directory where build script is located
cd "$(dirname "$0")"

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	tui-select.c -o ./tui-select.out

gcc \
	-O2 -Wall -Wextra -Werror -std=c99 -pedantic \
	tui-pane.c -o ./tui-pane.out

sudo cp ./tui-select.out /usr/local/bin/tui-select
sudo cp ./tui-pane.out /usr/local/bin/tui-pane

echo "tui/build: installed tui-select in /usr/local/bin/tui-select"
echo "tui/build: installed tui-pane in /usr/local/bin/tui-pane"
