[package]
name = "hnt-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
common-path = "1.0.0"

[lib]

[[bin]]
name = "llm-pack"
path = "src/main.rs"
