#!/bin/sh -e

if ! which uv > /dev/null 2>&1
then
	echo "build: uv is required"
	exit 1
fi

cd "$(dirname "$0")"

f=/tmp/hlmd-st
cp ./hlmd-st.py "$f"
chmod +x "$f"
sudo mv "$f" /usr/local/bin/

which hlmd-st > /dev/null
echo "build: hlmd-st installed" | hlmd-st
